stages:
  - format
  - lint
  - build

rustfmt:
  stage: format
  image: rustlang/rust:nightly
  script:
    - rustup component add rustfmt
    - cargo fmt --check

clippy:
  stage: lint
  image: rustlang/rust:nightly
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features

# rust-latest:
#   stage: build
#   image: rust:latest
#   script:
#     - cargo build --verbose
#     - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true
